<?php

$title = 'Home';
$this->headTitle($title, 'APPEND');
echo "<h2>$title</h2>\n";

?>

<p><a href="/tickets/submit">Submit a ticket</a></p>

<?php if (count($this->tickets) == 0): ?>
    <p>There are no tickets currently in the system</p>
<?php else: ?>
        <table>
            <tr>
                <th>Id</th>
                <th>Type</th>
                <th>Impact</th>
                <th>Status</th>
                <th>Submitted</th>
            </tr>
    <?php foreach ($this->tickets as $ticket): ?>
            <tr>
                <td>
                    <a href="/tickets/view/ticket/<?php echo $this->escape($ticket['ticketId']); ?>">
                <?php echo $this->escape($ticket['ticketId']); ?>
            </a>
        </td>
        <td><?php echo $this->escape($ticket['problemType']); ?></td>
        <td><?php echo $this->escape($ticket['impact']); ?></td>
        <td><?php echo $this->escape($ticket['status']); ?></td>
        <td><?php echo date('m-d-Y g:i a', strtotime($ticket['createdDate'])); ?></td>
    </tr>
    <?php endforeach; ?>
            </table>

<?php endif; ?>