<?php
if ($this->ticketNotFound) {
    $title = 'Edit Ticket';
    $this->headTitle($title, 'APPEND');
    echo '<p>' . $this->ticketNotFound . "</p>\n";
} else {
    $title = 'Edit Ticket ' . $this->escape($this->ticket['ticketId']);
    $this->headTitle($title, 'APPEND');
?>
    <p>
        Submitted by <strong><?php echo $this->escape($this->ticket['createdByUsername']); ?></strong>
        at <?php echo date('m-d-Y g:i a', strtotime($this->ticket['createdDate'])); ?>
    </p>

<?php
    echo $this->form->render();
}