<?php
$title = 'Search Tickets';
$this->headTitle($title, 'APPEND');
echo "<h2>$title</h2>\n";

echo $this->form->render();

if (!$this->searchResults):
?>
    <p>No tickets match your search parameters</p>
<?php else: ?>
    <h2>Search Results</h2>
        <table>
            <tr>
                <th>Id</th><th>Type</th><th>Impact</th><th>Status</th><th>Submitted</th>
            </tr>
    <?php foreach ($this->searchResults as $ticket): ?>
            <tr>
                <td>
                    <a href="/tickets/view/ticket/<?php echo $this->escape($ticket['ticketId']); ?>">
                <?php echo $this->escape($ticket['ticketId']); ?>
            </a>
        </td>
        <td><?php echo $this->escape($ticket['problemType']); ?></td>
        <td><?php echo $this->escape($ticket['impact']); ?></td>
        <td><?php echo $this->escape($ticket['status']); ?></td>
        <td><?php echo date('m-d-Y g:i a', strtotime($ticket['createdDate'])); ?></td>
    </tr>
    <?php endforeach; ?>
            </table>

<?php endif; ?>