<?php
if (!$this->ticket):
    $title = 'Ticket Not Found';
    $this->headTitle($title, 'APPEND');
    echo '<p>The ticket you requested could not be found.  Please try again.</p>';
else:
    $title = 'Ticket ' . $this->escape($this->ticket['ticketId']);
    $this->headTitle($title, 'APPEND');
?>

<?php if ($this->isAdminUser): ?>
        <p><a href="/tickets/modify/ticket/<?php echo $this->escape($this->ticket['ticketId']); ?>">Edit</a></p>
<?php endif; ?>

        <table>
            <tr>
                <td class="title">Ticket Id</td>
                <td><?php echo $this->escape($this->ticket['ticketId']); ?></td>
            </tr>
            <tr>
                <td class="title">Type</td>
                <td><?php echo $this->escape($this->ticket['problemType']); ?></td>
            </tr>
            <tr>
                <td class="title">Description</td>
                <td><?php echo $this->escape($this->ticket['problemDescription']); ?></td>
            </tr>
            <tr>
                <td class="title">Impact</td>
                <td><?php echo $this->escape($this->ticket['impact']); ?></td>
            </tr>
            <tr>
                <td class="title">Assigned To</td>
                <td><?php echo $this->escape($this->ticket['assignedTo']); ?></td>
            </tr>
            <tr>
                <td class="title">Status</td>
                <td><?php echo $this->escape($this->ticket['status']); ?></td>
            </tr>
            <tr>
                <td class="title">Notes</td>
                <td><?php echo $this->escape($this->ticket['notes']); ?></td>
            </tr>
            <tr>
                <td class="title">Created By</td>
                <td><?php echo $this->escape($this->ticket['createdBy']); ?></td>
            </tr>
            <tr>
                <td class="title">Created Date</td>
                <td><?php echo date('m-d-Y g:i a', strtotime($this->ticket['createdDate'])); ?></td>
            </tr>
            <tr>
                <td class="title">Last Updated By</td>
                <td><?php echo $this->escape($this->ticket['lastUpdatedBy']); ?></td>
            </tr>
            <tr>
                <td class="title">Last Updated Date</td>
                <td><?php echo date('m-d-Y g:i a', strtotime($this->ticket['lastUpdatedDate'])); ?></td>
            </tr>
        </table>

<?php
        endif;