<?php echo $this->doctype() ?>

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headScript(); ?>
    </head>
    <body>
        <!-- layouts/scripts/layout.phtml -->
        <div class="container_12">

            <div id="header" class="grid_12">
                <h1>Jeera Ticket Tracker</h1>
                <?php echo $this->loggedInAs(); ?>
            </div>

            <div class="clear"></div>

            <div id="navigation" class="grid_12">
                <?php echo $this->navigation()->menu(); ?>
            </div>

            <div class="clear"></div>

            <div id="content" class="grid_12">
                <?php echo $this->layout()->content; ?>
            </div>

            <div class="clear"></div>
        </div>
    </body>
</html>
